### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by martinRenou**
Fix https://github.com/jupyterlite/xeus/issues/17

TODO:
- [x] Document extra mount points
- [x] Document mounting jupyterlite content
- [x] Use jupyterlite and xeus logos

### CODE REVIEW

**Comment by martinRenou** [comment]
Let's write a bit more about mount points once https://github.com/jupyterlite/xeus/issues/45 is resolved

**Review by jtpio — APPROVED** [review]
Looks good for a first pass, thanks!

Maybe we can also update this page in the main JupyterLite documentation? https://jupyterlite.readthedocs.io/en/stable/howto/xeus-python/preinstalled_packages.html

**Comment by jtpio** [comment]
Also would it be possible to be added to the project on ReadTheDocs? (just in case and to increase the number of maintainers)

**Comment by martinRenou** [comment]
Sounds good! Thank

**Pull request merged**
