### PR TITLE
Bump empack

### PR DESCRIPTION
**Pull request by trungleduc**

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
CI failures look legit:

```

    def write_minimal_conda_meta(pkg_meta, env_prefix):
>       content = {k: pkg_meta[k] for k in ["name", "version", "build", "build_number", "url"]}
E       KeyError: 'url'

../../../../micromamba/envs/xeus-lite-dev/lib/python3.12/site-packages/empack/filter_env.py:76: KeyError
```

**Comment by trungleduc** [comment]
fixed in https://github.com/emscripten-forge/empack/pull/110

**Comment by trungleduc** [comment]
it's green

**Review by martinRenou — APPROVED** [review]
Thanks!

**Pull request merged**
